# Broadcasting

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


An operation on two numpy arrays with same shape results to the sum of each element of each index. 
To make the previous addition possible with two arrays of elements of different shapes, we have to use **broadcasting**.

In [2]:
a = np.array([1, 2, 3])
b = np.array([4])
print(a + b)


[5 6 7]


The result here is the individual three elements of the first array added to the element of the second array. 

In [3]:
a = np.array([1, 2, 3]) # (3, )
b = np.array([[4], [5]]) # (2, 1)
print(a + b)

[[5 6 7]
 [6 7 8]]
