# Numpy Arrays

In [48]:
import numpy as np 

In [49]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a[1])
print(a[1:])
print(a[:-2])

a[2] = 10 
print(a)


[1 2 3 4 5]
<class 'numpy.ndarray'>
2
[2 3 4 5]
[1 2 3]
[ 1  2 10  4  5]


In [50]:
a_mul = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a_mul)
print(a_mul[0])
print(a_mul[0, 1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2


# Array attributes

In [51]:
b_mul = np.array([[[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],
                   [[1, 1, 1, 1], 
                    [2, 2, 2, 2],
                    [3, 3, 3, 3]]])

print(a_mul.shape)
print(b_mul.shape)
print(a_mul.ndim)
print(b_mul.ndim)
print(a_mul.size)
print(b_mul.size)
print(a_mul.dtype)
print(b_mul.dtype)

(3, 3)
(2, 3, 4)
2
3
9
24
int64
int64


# Numpy Data Types

In [52]:
c = np.array([[1, 2, 3],
              [4, "Hello",  6],
              [7, 8, 9]])

print(c.dtype)
print(c[0][0])
print(type(c[0][0]))

<U21
1
<class 'numpy.str_'>


In [53]:
d = np.array([[1, 2, 3],
              [4, "5", 6],
              [7, 8, 9]], dtype=np.float32)

print(type(d[0][0]))
print(d[1][1].dtype)
print(d[1, 1])

<class 'numpy.float32'>
float32
5.0


In [54]:
e = {'1': 'A'}
e = np.array([[1, 2, 3], 
              [4, e, 6],
              [7, 8, 9]])

print(e.dtype)

object


# Filling arrays

In [55]:
a = np.full((2, 3 , 4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [56]:
a = np.zeros((10, 5, 2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [57]:
a = np.ones((10, 5, 2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [58]:
a = np.empty((2, 2, 2))
a

array([[[4.9e-324, 1.5e-323],
        [2.0e-323, 2.5e-323]],

       [[3.0e-323, 3.5e-323],
        [4.0e-323, 4.4e-323]]])

In [59]:
x_values = np.arange(0, 1000, 5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [60]:
x_values = np.linspace(0, 1000, 10)
print(x_values)

[   0.          111.11111111  222.22222222  333.33333333  444.44444444
  555.55555556  666.66666667  777.77777778  888.88888889 1000.        ]


In [61]:
print(np.nan)
print(np.inf)

nan
inf


In [62]:
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [63]:
print(np.isnan(np.sqrt(-1)))
print(np.isinf(np.array([10]) / 0))

True
[ True]


/tmp/ipykernel_21571/1011850589.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
/tmp/ipykernel_21571/1011850589.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10]) / 0))


# Mathematical operations

In [64]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]

a1 = np.array(l1)
a2 = np.array(l2)

print(a1)
print(a2)

print(l1 * 5)
print(a1 * 5)
print(a1 + 5)

print(l1 + l2)
print(a1 + a2)
print(a1 * a2)


[1 2 3 4 5]
[6 7 8 9 0]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[ 6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 7  9 11 13  5]
[ 6 14 24 36  0]


In [65]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1], [2]])

print(a1 + a2)

[[2 3 4]
 [3 4 5]]


In [66]:
a = np.array([[1, 2 , 3],
              [4, 5, 6]])

print(np.sqrt(a))
print(np.cos(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [67]:
a = np.array([1, 2, 3])

np.append(a, [7, 8, 9])
print(a)
a = np.append(a, [7, 8, 9])
print(a)

a = np.insert(a, 3, [4, 5, 6])
print(a)


[1 2 3]
[1 2 3 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [68]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b)
print(b.ravel())
print(np.delete(b, 1))
print(np.delete(b, 1, axis=1))
print(np.delete(b, 1, axis=0))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 3 4 5 6]
[[1 3]
 [4 6]]
[[1 2 3]]


Si aucun axis n'est spécifié, alors la fonction delete remet un élément à plat et le supprime. Cela revient à appliquer `b.ravel()` avant de supprimer.

# Structuring methods

In [90]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(a.shape)
print(a.reshape((5, 4))) # We transform this 4 lists of 5 elements array in a 5 lists of 4 elements array
print(a.reshape((20,))) # Without specifying more than 2 elements, it considers to turn the array to a unidimensionnal with the number of elements
print(a.reshape(2, 10))
print(a.reshape(2, 2, 5)) # Two collections with two lists each with five elements each
a.reshape(5, 4)
print(a)
a = a.reshape((5, 4)) # Has to be reassigned
print(a)

a.resize(10, 2) # Do not has to be reassigned
print(a)

print(a.flatten())
print(a.ravel())


(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


To illustrate de difference between `a.flatten()` and `a.ravel()` : 
- With flatten, the original array is not changed
- With ravel, the original array is changed

In [92]:
var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [94]:
var1 = a.ravel()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2]
 [100   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]]


In [96]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

var = [v for v in a.flat]
print(var)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


In [98]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(a.transpose())
print(a.swapaxes(0, 1))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [108]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

b = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

c = np.concatenate((a, b), axis=0)
print(c)
c = np.concatenate((a, b), axis=1)
print(c)

c = np.stack((a, b))
print(c)

c = np.vstack((a, b))
print(c)

c = np.hstack((a, b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [111]:
a = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24]])

print(np.split(a, 2, axis=1))

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]


# Aggregate functions

In [114]:
a = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24]])

print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
24
12.5
6.922186552431729
300
12.5


# Numpy Random

In [136]:
number = np.random.randint(100)
print(number)

72


In [138]:
numbers = np.random.randint(100, size=(2, 3, 4))
print(numbers)

[[[78 85 48  5]
  [ 7 43 97 93]
  [13 49 96 54]]

 [[60 85  1 97]
  [48 42 96 26]
  [64 22 47 58]]]


In [139]:
numbers = np.random.choice([10, 20, 30, 40, 50], size=(5, 10))
print(numbers)

[[50 10 10 30 40 20 50 10 50 10]
 [10 30 50 10 20 10 30 10 50 50]
 [10 30 20 50 20 20 30 10 20 50]
 [10 20 40 40 20 50 10 30 20 30]
 [20 30 30 40 30 20 10 30 10 30]]


# Importing / Exporting Numpy Arrays

In [142]:
print(a)
np.save("myarray.npy", a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [141]:
a = np.load("myarray.npy")
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [143]:
np.savetxt("myarray.csv", a, delimiter=",")

In [144]:
np.loadtxt("myarray.csv", delimiter=",")
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
